version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gaingrid-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gaingrid
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gaingrid-network

networks:
  gaingrid-network:
    driver: bridge

volumes:
  postgres_data:
